@host=http://localhost:1488
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU5NjA2ODMsImp0aSI6IjEiLCJpYXQiOjE3MjU4NzQyODN9.-CGcU6Dhx2YqjiU4eVfmyjbMrdHI6y-Ny5lmOoOQ8Rc

###

# Get all aliases
GET {{host}}/aliases

###

# Create new alias
POST {{host}}/alias

{
  "target": "12",
  "name": "new alias"
}

###

DELETE {{host}}/alias/id

###

# Get user resources
GET  {{host}}/resource
Authorization: Bearer {{token}}

###

# Create resource
POST {{host}}/resource/create
Authorization: Bearer {{token}}

{
  "content": "lorem ipsum"
}

###

# Delete specified resource
DELETE {{host}}/resource/delete/3
Authorization: Bearer {{token}}

###

POST {{host}}/resource/edit
Authorization: Bearer {{token}}

{
  "id": 2,
  "content": "New content\nReally new"
}

###

# Get user id based on username
POST {{host}}/auth

{
  "username": "user1"
}

###

# Get users
GET {{host}}/users

###

# Create new user
POST {{host}}/user/new

{
  "name": "Katy248",
  "password": "pass"
}

###

GET {{host}}/user/data
Authorization: Bearer {{token}}

###

# Update user data
POST {{host}}/user/change/name

{
  "id": "userId",
  "newUsername": "CoolerUsername"
}

###

# Delete user by id
DELETE {{host}}/user

{
  "id": "user id"
}


###

POST {{host}}/auth

{
  "name": "Katy248",
  "password": "pass"
}
