@host=http://localhost:1488
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjU5NTIzNDcsImp0aSI6IjIiLCJpYXQiOjE3MjU4NjU5NDd9.7fahdusdclvDje5A1YCaewB_vzE5CWwZ_plu1HPSagA

###

# Get all aliases
GET {{host}}/aliases

###

# Create new alias
POST {{host}}/alias

{
  "target": "12",
  "name": "new alias"
}

###

DELETE {{host}}/alias

{
  "id": "12"
}

###

# Get specified resource
GET  {{host}}/resource

{
  "name": "name"
}
# name can be alias

###

# Create resource
POST {{host}}/resource/create
Authorization: Bearer {{token}}

{
  "name": "name",
  "content": "lorem ipsum"
}

###

# Delete specified resource
DELETE {{host}}/resource

{
  "id": "id",
  "userId": "user_id"
}

###

# Get user id based on username
POST {{host}}/auth

{
  "username": "user1"
}

###

# Get users
GET {{host}}/users

###

# Create new user
POST {{host}}/user/new

{
  "name": "Katy248",
  "password": "pass"
}

###

GET {{host}}/user/data
Authorization: Bearer {{token}}

###

# Update user data
POST {{host}}/user/update

{
  "id": "userId",
  "newUsername": "CoolerUsername"
}

###

# Delete user by id
DELETE {{host}}/user

{
  "id": "user id"
}


###

POST {{host}}/auth

{
  "name": "Katy248",
  "password": "pass"
}
